// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.6.1
// source: thumq.proto

package thumq

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request_Crop int32

const (
	Request_NO_CROP    Request_Crop = 0
	Request_TOP_SQUARE Request_Crop = 1
)

// Enum value maps for Request_Crop.
var (
	Request_Crop_name = map[int32]string{
		0: "NO_CROP",
		1: "TOP_SQUARE",
	}
	Request_Crop_value = map[string]int32{
		"NO_CROP":    0,
		"TOP_SQUARE": 1,
	}
)

func (x Request_Crop) Enum() *Request_Crop {
	p := new(Request_Crop)
	*p = x
	return p
}

func (x Request_Crop) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Crop) Descriptor() protoreflect.EnumDescriptor {
	return file_thumq_proto_enumTypes[0].Descriptor()
}

func (Request_Crop) Type() protoreflect.EnumType {
	return &file_thumq_proto_enumTypes[0]
}

func (x Request_Crop) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Crop.Descriptor instead.
func (Request_Crop) EnumDescriptor() ([]byte, []int) {
	return file_thumq_proto_rawDescGZIP(), []int{0, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scale uint32       `protobuf:"varint,1,opt,name=scale,proto3" json:"scale,omitempty"`
	Crop  Request_Crop `protobuf:"varint,2,opt,name=crop,proto3,enum=thumq.Request_Crop" json:"crop,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thumq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_thumq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_thumq_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Request) GetCrop() Request_Crop {
	if x != nil {
		return x.Crop
	}
	return Request_NO_CROP
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceType string `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	NailWidth  uint32 `protobuf:"varint,2,opt,name=nail_width,json=nailWidth,proto3" json:"nail_width,omitempty"`
	NailHeight uint32 `protobuf:"varint,3,opt,name=nail_height,json=nailHeight,proto3" json:"nail_height,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thumq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_thumq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_thumq_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Response) GetNailWidth() uint32 {
	if x != nil {
		return x.NailWidth
	}
	return 0
}

func (x *Response) GetNailHeight() uint32 {
	if x != nil {
		return x.NailHeight
	}
	return 0
}

var File_thumq_proto protoreflect.FileDescriptor

var file_thumq_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x68, 0x75, 0x6d, 0x71, 0x22, 0x6d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x71, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x6f, 0x70, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x70, 0x22, 0x23,
	0x0a, 0x04, 0x43, 0x72, 0x6f, 0x70, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x43, 0x52, 0x4f,
	0x50, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x51, 0x55, 0x41, 0x52,
	0x45, 0x10, 0x01, 0x22, 0x6b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6e, 0x61, 0x69, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x42, 0x1a, 0x5a, 0x18, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x69, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x74, 0x68, 0x75, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thumq_proto_rawDescOnce sync.Once
	file_thumq_proto_rawDescData = file_thumq_proto_rawDesc
)

func file_thumq_proto_rawDescGZIP() []byte {
	file_thumq_proto_rawDescOnce.Do(func() {
		file_thumq_proto_rawDescData = protoimpl.X.CompressGZIP(file_thumq_proto_rawDescData)
	})
	return file_thumq_proto_rawDescData
}

var file_thumq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_thumq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thumq_proto_goTypes = []interface{}{
	(Request_Crop)(0), // 0: thumq.Request.Crop
	(*Request)(nil),   // 1: thumq.Request
	(*Response)(nil),  // 2: thumq.Response
}
var file_thumq_proto_depIdxs = []int32{
	0, // 0: thumq.Request.crop:type_name -> thumq.Request.Crop
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_thumq_proto_init() }
func file_thumq_proto_init() {
	if File_thumq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thumq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thumq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thumq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thumq_proto_goTypes,
		DependencyIndexes: file_thumq_proto_depIdxs,
		EnumInfos:         file_thumq_proto_enumTypes,
		MessageInfos:      file_thumq_proto_msgTypes,
	}.Build()
	File_thumq_proto = out.File
	file_thumq_proto_rawDesc = nil
	file_thumq_proto_goTypes = nil
	file_thumq_proto_depIdxs = nil
}
